services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./data/prod.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    command: >
      sh -c "
        npx prisma db push &&
        node server.js
      "

volumes:
  data: