version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./data/prod.db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-super-secret-key-change-this-in-production
      # Remplacez par vos vraies clés OAuth
      - GITHUB_ID=your-github-client-id
      - GITHUB_SECRET=your-github-client-secret
      - GOOGLE_ID=your-google-client-id
      - GOOGLE_SECRET=your-google-client-secret
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    command: >
      sh -c "
        npx prisma db push &&
        node server.js
      "

volumes:
  data: